language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Sz9Ilsz4Acr6Th01FNSAM+YLRN5CrqkoVztI4JnkN3ulxOv834tMsGbuDxFqP6ItizF1PmJrISJkjeh8w38N9oWQrTkaBO4aKdybSGAlYxWENIhX0isfYGqOokt8RFHDlsNHrIIxsCoeHVDldxT8sTqNDCDjZAwsscC4U9VjrCiIXpc+OVl4vFVbeJYVljLBxIWjw8FU3bp5uQBOsdkvmmJ6iEPshtp8JSqP85LTSkriiVGkfjsrH8VkCnwnxcEoFNwBeSqZs28840Me51me6BI1NgLRgP3RsXbAlb6TqhsB9J/FllGxF8koKTQ5MZtVPQDYYUEqs3RQqXsMVeRfNuUsxQe78M0NBZB5I69k/Wcr5SqOuUp2PXJL04GCY+37P0bj7glYoCd6oehU/6IgznXG1P8vQbSdOWDz0RHsqJkRPFlpNhjU31Uxf5z2rFzYWpjJlq/KhMMXI6+aVssJlZINr3wstDiVQiMMu7bRUqjz9zyj5724FAee6cmlw+QLdPF6ttpgh7zW12AVi8CdSgF4ddieBDfxPJ8E1JTfKBEpr0DsQ4UKBZnvp+jZ++EtSqNe59S9kGkHw9IiYzVC/4JZ3L5K8PKzjW2X5PKsDW512vrJL2fayAFnbBYnfaBJwzTEYQKAmcMA3gthO0o0ai7d1CCayFRMlG+QlGLytXk=
  app: tricia-scott-mongoose-tests
  on:
    repo: thinkful-ei17/tricia-scott-mongoose-tests
